#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const { compile } = require('json-schema-to-typescript');
const { GENERATED_ASSETS } = require('./data/constants.cjs');

const HEADER = '// This file is generated by scripts/generate_asset_types.cjs. Do not edit manually.\n\n';

function outputRootFromArgs(argv) {
  const index = argv.indexOf('--output-root');
  return index >= 0 ? path.resolve(argv[index + 1]) : process.cwd();
}

async function generateAssetTypes({ sourceRoot = process.cwd(), outputRoot = sourceRoot } = {}) {
  const schema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'LeagueAssetBundle',
    type: 'object',
    additionalProperties: false,
    required: ['h2h', 'seasonSummary', 'rivalries', 'currentSeason', 'shotguns', 'draftSpot', 'derivedStats', 'assetManifest'],
    properties: {
      h2h: { $ref: 'h2h.schema.json' },
      seasonSummary: { $ref: 'season-summary.schema.json' },
      rivalries: { $ref: 'rivalries.schema.json' },
      currentSeason: { $ref: 'current-season.schema.json' },
      shotguns: { $ref: 'shotguns.schema.json' },
      draftSpot: { $ref: 'draft-spot.schema.json' },
      derivedStats: { $ref: 'derived-stats.schema.json' },
      assetManifest: { $ref: 'asset-manifest.schema.json' },
    },
  };
  const generated = await compile(schema, 'LeagueAssetBundle', {
    bannerComment: '',
    cwd: path.join(sourceRoot, 'schemas'),
    style: { singleQuote: true, semi: true, tabWidth: 2, trailingComma: 'all' },
    unknownAny: false,
  });
  const outputPath = path.join(outputRoot, GENERATED_ASSETS.AssetTypes.path);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `${HEADER}${generated.trim()}\n`);
  return outputPath;
}

if (require.main === module) {
  generateAssetTypes({ outputRoot: outputRootFromArgs(process.argv.slice(2)) })
    .then(output => console.log(`Generated ${path.relative(process.cwd(), output)}`))
    .catch(error => { console.error(error.message || error); process.exit(1); });
}

module.exports = { generateAssetTypes, outputRootFromArgs };
